### PR TITLE
Improve communications page

### PR DESCRIPTION
**Pull request by MaartenS11**
This PR improves the communications page by adjusting styling and layout of certain components and adding a timestamp to each communication. Without the timestamp all communications would just be placed randomly. By having a timestamp users can see when a communication was registered and the last communication to each student is always shown first.

**Breaking change checklist**:
- [x] I've updated the existing tests to account for the changes in expected behaviour
- [x] I've updated the documentation to reflect the new behaviour
- [x] I've updated the `osoc.yaml` file
- [x] I've updated the frontend to make use of the timestamp field, alongside improving the communications page UI

### CODE REVIEW

**Comment by MaartenS11** [comment]
If you can centre the name vertically in the column (while keeping the delete button on the same row) feel free to let me know.

**Review by lars-vc — APPROVED** [review]

**Comment by NielsPraet** [comment]
Don't these changes break the population script @lars-vc @MaartenS11 ?

**Comment by MaartenS11** [comment]
> Don't these changes break the population script @lars-vc @MaartenS11 ?

They shouldn't, the requests are still exactly the same. The backend generates the timestamp on arrival of the request, so it's just an extra field returned in the response.

**Review by NinjaJay — APPROVED** [review]

**Comment by Mikxox** [comment]
> If you can centre the name vertically in the column (while keeping the delete button on the same row) feel free to let me know.

You can do this

```
      <td className="m-auto py-4 pl-3">
        <div className="flex flex-row">
          {studentName}
          {hovering && (
            <TrashIcon
              className="h-6 w-6 pl-1 hover:cursor-pointer"
              color="#F14A3B"
              onClick={() => {
                setCommsToDelete(commsId);
                setShowDeleteForm(true);
              }}
            />
          )}
        </div>
      </td>
```

**Pull request merged**
