### PR TITLE
feat: reroute on index page

### PR DESCRIPTION
**Pull request by NielsPraet**
Redirect on index page

Active edition? Reroute to projects page

No active edition? 
   - Disabled Role? Wait Page
   - Coach Role? Users Page
   - Admin Role? Editions Page

### CODE REVIEW

**Comment by Mikxox** [comment]
Login currently redirects coach with no active edition to /wait so you can probably change that to the Users page as well

**Review by Mikxox — APPROVED** [review]

**Comment by NielsPraet** [comment]
> Login currently redirects coach with no active edition to /wait so you can probably change that to the Users page as well? What happens when a coach with no active edition clicks on students or projects link in the header? might give an error but tbh I don't think that is worth caring about.

The header checks if an edition is present and updates the links accordingly

> Minor thing, currently when you are not logged in and go to index page, you get moved to /wait and then instantly redirected to /login

Ye I saw that too, very weird

**Comment by Mikxox** [comment]
> > Minor thing, currently when you are not logged in and go to index page, you get moved to /wait and then instantly redirected to /login
> 
> Ye I saw that too, very weird

Probably since both disabled and not logged in use default, maybe add a role.disabled for /wait and a default to /login?

**Review by lars-vc — APPROVED** [review]

**Comment by lars-vc** [comment]
Can you fix the actions?

**Pull request merged**
