### PR TITLE
Better readable difference between positions

### PR DESCRIPTION
**Pull request by lars-vc**
Related to #303

### CODE REVIEW

**Comment by NinjaJay** [comment]
Is there a reason why sometimes the position box is very small and other times its big? Sometimes the position is also just on the edge of the box with no space between.
image
image

**Comment by lars-vc** [comment]
> Sometimes the position is just on the edge of the box with no space between. image

Oh there isn't supposed to be a box oops, didn't undo enough

**Comment by lars-vc** [comment]
Sadly, I didn't get it working the way that I wanted (lines of the same position being attachted instead of having a white line between them)

**Review by NinjaJay — APPROVED** [review]

**Comment by NielsPraet** [comment]
> Sadly, I didn't get it working the way that I wanted (lines of the same position being attachted instead of having a white line between them)

If you didn't get it working I think it would be better to keep it as it is now on the dev branch

**Comment by NinjaJay** [comment]
> > Sadly, I didn't get it working the way that I wanted (lines of the same position being attachted instead of having a white line between them)
> 
> If you didn't get it working I think it would be better to keep it as it is now on the dev branch

I don't think it's bad to put the amount of positions in bold

**Comment by lars-vc** [comment]
Ye the amount in bold does add clarity imo

**Review by NielsPraet — APPROVED** [review]

**Pull request merged**
