### PR TITLE
Delete users prompt

### LINKED ISSUE #251: Delete Users
Currently there is no way to delete users in the frontend, iirc this is a wanted feature. There exists a backend endpoint for this `DELETE /users/{id}`

### PR DESCRIPTION
**Pull request by NielsPraet**
### Checklist
**New feature checklist**:
- [x] I've thoroughly documented the code

Closes #251

### CODE REVIEW

**Comment by NinjaJay** [comment]
Do we really want to delete users, since if they did a statussuggestion, you also need to delete that, which isn't usefull if you want to look back to previous editions. That's why we have the disabled option on a user

**Comment by NinjaJay** [comment]
> Do we really want to delete users, since if they did a statussuggestion, you also need to delete that, which isn't usefull if you want to look back to previous editions. That's why we have the disabled option on a user

Apparently they want this, but this still erros if you try to delete a user who has done a suggestion. This is a backend error tho.

**Review by NinjaJay — APPROVED** [review]

**Review by NinjaJay — CHANGES_REQUESTED** [review]
If you press the delete button, a popup shows, but if you close the popup (deleting or not deleting), you can't scroll anymore (this is on chrome)

**Comment by NielsPraet** [comment]
> If you press the delete button, a popup shows, but if you close the popup (deleting or not deleting), you can't scroll anymore (this is on chrome)

This could have to do with the `lockScroll` attribute of the Popup. Being as this popup is a third party thing this might be on their end. If it continues to be a problem, I think it would be best to remove the attribute until this is fixed.
image

**Comment by lars-vc** [comment]
I have this scrolling issue on firefox too

**Comment by Mikxox** [comment]
I'm pretty certain the scrolling bug is due to how you're opening and closing the popup. I have the exact same issue with this popup but not with any of the other popups.

**Comment by TomAlard** [comment]
Deleting a coach with a status suggestion gives an unknown error instead of deleting the user.
Expected behavior when deleting a user with status suggestions: the user and all of his suggestions are deleted
Actual behavior: the user is not deleted, presumably due to the backend refusing to delete the user.

**Comment by lars-vc** [comment]
Scrolling works now! I'll approve since that deletion bug is backend based

**Review by lars-vc — APPROVED** [review]

**Review by NinjaJay — APPROVED** [review]

**Comment by Mikxox** [comment]
Can you undo the @ts-ignore in UsertableRow ? You can fix it by doing
```const message = (err.response?.data as {message: string}).message;```
on line 109-110

**Review by MaartenS11 — APPROVED** [review]
I'm not really an expert on frontend code, but this seems to look fine and it is also functional(besides backend issues) so I will approve this.

**Pull request merged**
