### PR TITLE
Communications page

### LINKED ISSUE #315: Communications Page
We need to create a communications page that lists all outgoing communications per student, this is something that the user themselves (if they are an admin) need to add.

- [x] ~~Before being able to create this page, we also need an endpoint that gives us **all** communications (Possibly something for @MaartenS11 or @lars-vc to look at). Also right now, there is no link between a communication and the student regarding this communication message, we need to add this relation to the database.~~
- [x] we could also use a visual presentation of this page on figma

### PR DESCRIPTION
**Pull request by NielsPraet**
### Checklist

**New feature checklist**:
- [x] I've thoroughly documented the code

Closes #315

### CODE REVIEW

**Comment by lars-vc** [comment]
Can you merge dev into this, this pr still has the editionless communications, so it's hard to test

**Review by lars-vc — APPROVED** [review]

**Comment by NielsPraet** [comment]
Waiting on #362 to fix deleting comms

**Review by tvhimme — APPROVED** [review]

**Comment by lars-vc** [comment]
#362 is merged, so do we merge this now? Also fix eslint and prettier please ;)

**Comment by MaartenS11** [comment]
image
Contrast on the disabled "Download CSV" is very low making it nearly unreadable.

**Comment by NielsPraet** [comment]
> image Contrast on the disabled "Download CSV" is very low making it nearly unreadable.

I know, I'm gonna fix this once I get feedback from some contrast checker application thingie or something

**Comment by NielsPraet** [comment]
@Mikxox Could you check if the deletion stuff works as it should?

**Comment by MaartenS11** [comment]
Another small piece of UI feedback, maybe already mentioned somewhere not sure. I think it would be useful to add a lable above this combobox because it's not exactly clear what this will contain untill you actually open the combobox options. It might also e better to move the information box below this comobox considering it is by default taller and can be made even taller than the comobobx.
image

**Pull request merged**
