### PR TITLE
Fix reloading issues

### PR DESCRIPTION
**Pull request by Mikxox**
This fixes the reloading issues,
I thing everything works now.
I also added a mutex around refreshing, to fix using different axiosauth instances since the sidebar & main view in for example projects would not share the same refresh request promise and would still fail.
I also had to add an ignore 401 error due to this.

~~I noticed the users & editions page doesn't work after a reload, I'll be fixing that~~ done

### CODE REVIEW

**Comment by lars-vc** [comment]
image
I got this on reloading on the projects page, which is bizar because this is the changed refresh token error

**Review by NinjaJay — COMMENTED** [review]
If I try reloading, then sometimes it errors and doesn't show any data.
image

**Comment by Mikxox** [comment]
> I got this on reloading on the projects page, which is bizar because this is the changed refresh token error

Should be fixed now by merging the other pr's

**Comment by Mikxox** [comment]
> If I try reloading, then sometimes it errors and doesn't show any data.
> 
> This may be the same issue as Lars but I didn't get that error popup

Should be fixed now by merging the other pr's

**Comment by lars-vc** [comment]
image
still got this when reloading on student page

**Comment by NinjaJay** [comment]
Same. I still get it too

**Review by lars-vc — APPROVED** [review]

**Review by NinjaJay — APPROVED** [review]
Sad that it doesn't work with yarn dev but it works when you fully build the project

**Pull request merged**
