### PR TITLE
Refreshtoken exception

### LINKED ISSUE #287: Bug: fix refresh token error code
Currently a failing refresh token returns a 400. But many more errors also return this status code. It would be optimal for the frontend to have a unique status code or some other unique identifier for when a refresh token request fails.

### PR DESCRIPTION
**Pull request by lars-vc**
Closes #287
@NielsPraet which statuscode would you like for this exception, I don't really see a fitting one that isn't being used already.
Also does this suffice, are these the only exceptions that need changing? I think these are the only ones that are directly related to the refreshtoken.

### CODE REVIEW

**Comment by Mikxox** [comment]
There is another error that returns a 400 bad request when a refresh token that is expired / already used, gets used. I'm not sure where that gets thrown though.

**Comment by lars-vc** [comment]
> There is another error that returns a 400 bad request when a refresh token that is expired / already used, gets used. I'm not sure where that gets thrown though. It returns the following so it might actually be alright image

This error is used both for access and refresh tokens, so don't know if you want it changed then?
image

**Comment by Mikxox** [comment]
> > There is another error that returns a 400 bad request when a refresh token that is expired / already used, gets used. I'm not sure where that gets thrown though. It returns the following so it might actually be alright
> 
> This error is used both for access and refresh tokens, so don't know if you want it changed then? 

I'm not certain what this change is going to be used for so you'll have to ask Niels what to do with that error.

**Comment by NielsPraet** [comment]
Yes just to be safe, change that one too. Also don't forget that it seems tests are failing

**Review by Mikxox — APPROVED** [review]

**Review by NielsPraet — APPROVED** [review]

**Pull request merged**
