### PR TITLE
Make header fixed

### PR DESCRIPTION
**Pull request by Mikxox**
This fixes part of #254 
This makes the header stay fixed at the top of the page & makes the studentsidebar not be longer than the page view.
I also added a title to the communications page
and fixed a margin on the students page & added a 'no suggestions yet' placeholder

This also makes tooltips have a low max width since they were bugging out page width.

### CODE REVIEW

**Review by lars-vc — APPROVED** [review]

**Review by NinjaJay — CHANGES_REQUESTED** [review]
The placeholder doesn't get removed if there are suggestions

image

**Comment by NielsPraet** [comment]
Can you check that this doesn't leed to strange behaviour with the sticky table header on the users page?

**Comment by Mikxox** [comment]
> The placeholder doesn't get removed if there are suggestions
> 

Is fixed now, I was doing a compare on the wrong thing

**Comment by Mikxox** [comment]
> Can you check that this doesn't leed to strange behaviour with the sticky table header on the users page?

I totally forgot those were sticky as well, they got hidden underneath the header, I fixed that now

**Review by NinjaJay — APPROVED** [review]

**Pull request merged**
